# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(288, 153)
        LoginDialog.setWhatsThis("")
        LoginDialog.setModal(True)
        self.loginBtn = QtWidgets.QPushButton(LoginDialog)
        self.loginBtn.setGeometry(QtCore.QRect(50, 110, 75, 23))
        self.loginBtn.setObjectName("loginBtn")
        self.accountEdit = QtWidgets.QLineEdit(LoginDialog)
        self.accountEdit.setGeometry(QtCore.QRect(80, 34, 171, 20))
        self.accountEdit.setObjectName("accountEdit")
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 54, 12))
        self.label.setObjectName("label")
        self.registerBtn = QtWidgets.QPushButton(LoginDialog)
        self.registerBtn.setGeometry(QtCore.QRect(150, 110, 75, 23))
        self.registerBtn.setObjectName("registerBtn")
        self.accountEdit_2 = QtWidgets.QLineEdit(LoginDialog)
        self.accountEdit_2.setGeometry(QtCore.QRect(80, 74, 171, 20))
        self.accountEdit_2.setObjectName("accountEdit_2")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 54, 12))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "用户"))
        self.loginBtn.setText(_translate("LoginDialog", "确定"))
        self.label.setText(_translate("LoginDialog", "用户名"))
        self.registerBtn.setText(_translate("LoginDialog", "返回"))
        self.label_2.setText(_translate("LoginDialog", "密码"))
